/* eslint-disable max-len */
export interface Product {
    id: number;
    catId: number;
    company: string;
    category: string;
    color: string;
    size: string;
    title: string;
    price: number;
    description: string;
    subCat: string;
    image: string;
    stock: number;
  }

export const products = [{
        id: 101,
        catId: 0,
        category: 'Men',
        company: 'HRX by Hrithik Roshan',
        color: 'White',
        size: 'One Size',
        title: 'Solid Round Neck T-shirt',
        price: 499,
        description : 'The feel of this HRX tee is absolutely amazing thanks to the use of polyester. This white item can be teamed with fitted jeans for a clean look or lounge shorts for casual weekend wear. This versatile T-shirt can be styled any way you like for the ultimate gym-to-street look.',
        subCat: 'Tshirts',
        image: '../../assets/images/Products/Men/Western/Tshirts/1.jpg',
        stock:100
    },
    {
        id: 102,
        catId: 0,
        category: 'Men',
        company: 'Roadster',
        color: 'Black',
        size: 'One Size',
        title: 'Rapid Dry Round Neck T-shirt',
        price: 199.00,
        description : 'Black solid T-shirt, has a round neck, and short sleeves. Made of cotton, you will love the high-quality fit and feel of this Roadster tee. When you are out running errands, you will look your best when you combine this black piece with your favourite pair of sunglasses and trainer shoes.',
        subCat: 'Tshirts',
        // eslint-disable-next-line max-len
        image: '../../assets/images/Products/Men/Western/Tshirts/2.jpg',
        stock:100
    },
    {
        id: 103,
        catId: 0,
        category: 'Men',
        company: 'H&M',
        color: 'Pink',
        size: 'One Size',
        title: 'Men Pink Solid Round Neck T-shirt',
        price: 599.00,
        description: 'Pink solid T-shirt, has a round neck, and short sleeves. Made of cotton, you will love the high-quality fit and feel of this H&M tee. Wear this pink piece many ways, with dark wash jeans, cuffed chinos and more.',
        subCat: 'Tshirts',
        image: '../../assets/images/Products/Men/Western/Tshirts/3.jpg',
        stock:100
    },
    {
        id: 104,
        catId: 0,
        category: 'Men',
        company: 'BerryCrush',
        color: 'Red',
        size: 'One Size',
        title: 'Printed Round Neck T-shirt',
        price: 599.00,
        description: 'Red printed T-shirt and has a round neck. Designed by the team at BerryCrush, you are definitely in for a style treat with this cotton T-shirt. You will feel entirely at ease in this red piece on top of a relaxed-fit chino and slip-on tennis shoe when you are going out shopping or catching a movie.',
        subCat: 'Tshirts',
        // eslint-disable-next-line max-len
        image: '../../assets/images/Products/Men/Western/Tshirts/4.jpg',
        stock:100
    },
    {
        id: 105,
        catId: 0,
        category: 'Men',
        company: 'Hancock',
        color: 'White',
        size: 'One Size',
        title: 'Blue & White Regular Fit Checked Cotton Casual Shirt',
        price: 899.00,
        description : ' Blue and White checked casual Shirts, has a button-down collar, long sleeves, button placket, and curved hem. Cozy up with this in-style Hancock shirt this season. For a night at the movies or casual dinner date, team this navy blue shirt with slim trousers and light jacket. ',
        subCat: 'Shirts',
        image: '../../assets/images/Products/Men/Western/Shirts/1.jpg',
        stock: 100
    },
    {
        id: 106,
        catId: 0,
        category: 'Men',
        company: 'Louise Philippe',
        color: 'White',
        size: 'One Size',
        title: 'Men White Slim Fit Solid Formal Shirt',
        price: 999.00,
        description: 'White solid formal shirt, has a spread collar, button placket, long sleeves, a patch pocket. Add class to your year-round style with this formal shirt from Louise Philippe. When you are attending a family outing, pair this white piece with slim jeans and easy loafers.',
        subCat: 'Shirts',
        image: '../../assets/images/Products/Men/Western/Shirts/2.jpg',
        stock:100
    },
    {
        id: 107,
        catId: 0,
        category: 'Men',
        company: 'Indian Terrain',
        color: 'Pink',
        size: 'One Size',
        title: 'Men Pink Solid Premium Cotton Formal Shirt',
        price: 1099,
        description : 'Pink solid formal shirt, has a spread collar, long sleeves, button placket, and curved hem. Add class to your year-round style with this formal shirt from Indian Terrain. This piece can be matched with formal trousers and a sleek blazer when you are heading to work.',
        subCat: 'Shirts',
        image: '../../assets/images/Products/Men/Western/Shirts/3.jpg',
        stock: 100
    },
    {
        id: 108,
        catId: 0,
        category: 'Men',
        company: 'Roadster',
        color: 'Yellow',
        size: 'One Size',
        title: 'Yellow Regular Fit Solid Trousers',
        price: 999,
        description : 'Yellow solid mid-rise trousers, drawstring closure, and 2 pockets. These classic trousers from Roadster will take your style to a whole new level. Create a business casual ensemble with this yellow pair when you throw on a pressed shirt and leather shoes.',
        subCat: 'Trousers',
        image: '../../assets/images/Products/Men/Western/Trousers/1.jpg',
        stock: 100
    },
    {
        id: 109,
        catId: 0,
        category: 'Men',
        company: 'Van Heusen',
        color: 'White',
        size: 'One Size',
        title: 'Men White Slim Fit Solid Regular Trousers',
        price: 3000.00,
        description : 'White solid trousers and button closure. Formalize your wardrobe with a fashionable pair of trousers by Van Heusen Sport. When you are celebrating your anniversary, match this white pair with your favourite shirt and a trendy tie.',
        subCat: 'Trousers',
        image: '../../assets/images/Products/Men/Western/Trousers/2.jpg',
        stock: 100
    },
    {
        id: 110,
        catId: 0,
        category: 'Men',
        company: 'Tommy Hilfiger',
        color: 'Black',
        size: 'One Size',
        title: 'Black Flared Solid Trousers',
        price: 3500.00,
        description : 'Black solid mid-rise flared regular trousers, slip-on closure. With these Tommy Hilfiger flared trousers, you can nail that runway look you have been wanting to try. No matter the top or blazer, they will go well with this solid black pair to craft elegant work-day attire.',
        subCat: 'Trousers',
        image: '../../assets/images/Products/Men/Western/Trousers/3.jpg',
        stock: 100
    },
    {
        id: 111,
        catId: 0,
        category: 'Men',
        company: 'Roadster',
        color: 'Blue',
        size: 'One Size',
        title: 'Blue Tapered Fit Mid-Rise Clean Look Stretchable Jeans',
        price: 2500.00,
        description: 'Blue medium wash 5-pocket mid-rise jeans, clean look, light fade, has a button and zip closure, and waistband with belt loops. These Roadster jeans will have you looking and feeling your best. Rock them with your favourite pair of canvas shoes and a printed tee for a laid-back lunch date ensemble.',
        subCat: 'Jeans',
        image: '../../assets/images/Products/Men/Western/Jeans/1.jpg',
        stock: 100
    },
    {
        id: 112,
        catId: 0,
        category: 'Men',
        company: 'Pepe Jeans',
        color: 'Black',
        size: 'One Size',
        title: 'Men Black Skinny Fit Jeans',
        price: 2000.00,
        description : 'Black dark wash jeans, clean look, no fade, has a zip fly closure, and waistband with belt loops. Sharpen up your personal style game with these Pepe Jeans skinny-fit jeans. Dress them down with a trendy T-shirt and some sneakers for a laid-back date night.',
        subCat: 'Jeans',
        image: '../../assets/images/Products/Men/Western/Jeans/2.jpg',
        stock: 100
    },
    {
        id: 113,
        catId: 0,
        category: 'Men',
        company: 'Van Heusen',
        color: 'Blue',
        size: 'One Size',
        title: 'Blue Beat Relaxed Fit Low-Rise Light Fade Stretchable Jeans',
        price: 5000.00,
        description : 'Medium light fade blue jeans. For long-lasting comfort and style, opt for these Van Heusen skinny-fit jeans. They can be worn with canvas shoes and a stylish tee for a night out on the town with your friends.',
        subCat: 'Jeans',
        image: '../../assets/images/Products/Men/Western/Jeans/3.jpg',
        stock: 100
    },
    {
        id: 114,
        catId: 0,
        category: 'Men',
        company: 'H&M',
        color: 'Green',
        size: 'One Size',
        title: 'Men Green Solid Regular Fit Single-Breasted Formal Blazer',
        price: 5000.00,
        description : 'H&M Professional green blazer. Goes best with blue shirt and gray striped tie. The blazer is a customer blazer with wide peak labels, pick stitching and contrast, functional button holes.',
        subCat: 'Blazers',
        image: '../../assets/images/Products/Men/Western/Blazers/1.jpg',
        stock: 100
    },
    {
        id: 115,
        catId: 0,
        category: 'Men',
        company: 'Ether',
        color: 'Blue',
        size: 'One Size',
        title: 'Men Blue Solid Single-Breasted Knitted Blazer',
        price: 8000.00,
        description : 'Blue solid single breasted casual blazer, has a notched lapel collar, button closure, long sleeves, three pockets, an attached lining with two built-in pockets',
        subCat: 'Blazers',
        image: '../../assets/images/Products/Men/Western/Blazers/2.jpg',
        stock: 100
    },
    {
        id: 116,
        catId: 0,
        category: 'Men',
        company: 'Raymond',
        color: 'Black',
        size: 'One Size',
        title: 'Black Single Breasted Super Slim Fit Blazer',
        price: 8000.00,
        description : 'Black solid single breasted blazer, has a notched lapel, long sleeves, three pockets, straight hem, attached satin lining. Set the trend with this blazer from Raymond. Team it up with trousers and a shirt to create a cool look.',
        subCat: 'Blazers',
        image: '../../assets/images/Products/Men/Western/Blazers/3.jpg',
        stock: 100
    },
    {
        id: 117,
        catId: 0,
        category: 'Men',
        company: 'Raymond',
        color: 'Black',
        size: 'One Size',
        title: 'Black Single Breasted Super Slim Fit Blazer',
        price: 1000.00,
        description : 'Black solid single breasted blazer, has a notched lapel, long sleeves, three pockets, straight hem, attached satin lining. Set the trend with this blazer from Raymond. Team it up with trousers and a shirt to create a cool look.',
        subCat: 'Kurta',
        image: '../../assets/images/Products/Men/Ethnic/Kurta/3.jpg',
        stock: 100
    },
    {
        id: 118,
        catId: 0,
        category: 'Men',
        company: 'Manyawar',
        color: 'Black',
        size: 'One Size',
        title: 'Black Single Breasted Super Slim Fit Blazer',
        price: 4500.00,
        description : 'Black solid single breasted blazer, has a notched lapel, long sleeves, three pockets, straight hem, attached satin lining. Set the trend with this blazer from Raymond. Team it up with trousers and a shirt to create a cool look.',
        subCat: 'Sherwani',
        image: '../../assets/images/Products/Men/Ethnic/Sherwani/1.jpg',
        stock: 100
    },
    {
        id: 119,
        catId: 0,
        category: 'Men',
        company: 'Benetton',
        color: 'Black',
        size: 'One Size',
        title: 'Black Single Breasted Super Slim Fit Blazer',
        price: 1500.00,
        description : 'Black solid single breasted blazer, has a notched lapel, long sleeves, three pockets, straight hem, attached satin lining. Set the trend with this blazer from Raymond. Team it up with trousers and a shirt to create a cool look.',
        subCat: 'Flip Flops',
        image: '../../assets/images/Products/Men/Footwear/Flip Flops/4.jpg',
        stock: 100
    },
    {
        id: 120,
        catId: 0,
        category: 'Men',
        company: 'Puma',
        color: 'Black',
        size: 'One Size',
        title: 'Black Single Breasted Super Slim Fit Blazer',
        price: 1500.00,
        description : 'Black solid single breasted blazer, has a notched lapel, long sleeves, three pockets, straight hem, attached satin lining. Set the trend with this blazer from Raymond. Team it up with trousers and a shirt to create a cool look.',
        subCat: 'Sandals',
        image: '../../assets/images/Products/Men/Footwear/Sandals/4.jpg',
        stock: 100
    },
    {
        id: 121,
        catId: 0,
        category: 'Men',
        company: 'Kook N Keech',
        color: 'Black',
        size: 'One Size',
        title: 'Black Single Breasted Super Slim Fit Blazer',
        price: 1500.00,
        description : 'Black solid single breasted blazer, has a notched lapel, long sleeves, three pockets, straight hem, attached satin lining. Set the trend with this blazer from Raymond. Team it up with trousers and a shirt to create a cool look.',
        subCat: 'Casual Shoes',
        image: '../../assets/images/Products/Men/Footwear/Casual Shoes/1.jpg',
        stock: 100
    },
    {
        id: 122,
        catId: 0,
        category: 'Men',
        company: 'Nike',
        color: 'Black',
        size: 'One Size',
        title: 'Black Single Breasted Super Slim Fit Blazer',
        price: 6500.00,
        description : 'Black solid single breasted blazer, has a notched lapel, long sleeves, three pockets, straight hem, attached satin lining. Set the trend with this blazer from Raymond. Team it up with trousers and a shirt to create a cool look.',
        subCat: 'Sports Shoes',
        image: '../../assets/images/Products/Men/Footwear/Sports Shoes/1.jpg',
        stock: 100
    },
    {
        id: 123,
        catId: 0,
        category: 'Men',
        company: 'Van Heusen',
        color: 'Blue',
        size: 'One Size',
        title: 'Black Single Breasted Super Slim Fit Blazer',
        price: 6500.00,
        description : 'Black solid single breasted blazer, has a notched lapel, long sleeves, three pockets, straight hem, attached satin lining. Set the trend with this blazer from Raymond. Team it up with trousers and a shirt to create a cool look.',
        subCat: 'Tie',
        image: '../../assets/images/Products/Men/Accessories/Tie/1.jpg',
        stock: 100
    },
    {
        id: 124,
        catId: 0,
        category: 'Men',
        company: 'Allen Solly',
        color: 'Brown',
        size: 'One Size',
        title: 'Black Single Breasted Super Slim Fit Blazer',
        price: 2500.00,
        description : 'Black solid single breasted blazer, has a notched lapel, long sleeves, three pockets, straight hem, attached satin lining. Set the trend with this blazer from Raymond. Team it up with trousers and a shirt to create a cool look.',
        subCat: 'Wallet',
        image: '../../assets/images/Products/Men/Accessories/Wallet/1.jpg',
        stock: 100
    },
    {
        id: 125,
        catId: 0,
        category: 'Men',
        company: 'Adidas',
        color: 'Blue',
        size: 'One Size',
        title: 'Black Single Breasted Super Slim Fit Blazer',
        price: 6500.00,
        description : 'Black solid single breasted blazer, has a notched lapel, long sleeves, three pockets, straight hem, attached satin lining. Set the trend with this blazer from Raymond. Team it up with trousers and a shirt to create a cool look.',
        subCat: 'Cap',
        image: '../../assets/images/Products/Men/Accessories/Cap/1.jpg',
        stock: 100
    },
    {
        id: 201,
        catId: 0,
        category: 'Women',
        company: 'Raymond',
        color: 'Black',
        size: 'One Size',
        title: 'Black Single Breasted Super Slim Fit Blazer',
        price: 8000.00,
        description : 'Black solid single breasted blazer, has a notched lapel, long sleeves, three pockets, straight hem, attached satin lining. Set the trend with this blazer from Raymond. Team it up with trousers and a shirt to create a cool look.',
        subCat: 'Tshirts',
        image: '../../assets/images/Products/Women/Western/Tshirts/1.jpg',
        stock: 100
    },
    {
        id: 202,
        catId: 0,
        category: 'Women',
        company: 'Raymond',
        color: 'Black',
        size: 'One Size',
        title: 'Black Single Breasted Super Slim Fit Blazer',
        price: 8000.00,
        description : 'Black solid single breasted blazer, has a notched lapel, long sleeves, three pockets, straight hem, attached satin lining. Set the trend with this blazer from Raymond. Team it up with trousers and a shirt to create a cool look.',
        subCat: 'Tshirts',
        image: '../../assets/images/Products/Women/Western/Tshirts/2.jpg',
        stock: 100
    },
    {
        id: 203,
        catId: 0,
        category: 'Women',
        company: 'Raymond',
        color: 'Black',
        size: 'One Size',
        title: 'Black Single Breasted Super Slim Fit Blazer',
        price: 8000.00,
        description : 'Black solid single breasted blazer, has a notched lapel, long sleeves, three pockets, straight hem, attached satin lining. Set the trend with this blazer from Raymond. Team it up with trousers and a shirt to create a cool look.',
        subCat: 'Tshirts',
        image: '../../assets/images/Products/Women/Western/Tshirts/3.jpg',
        stock: 100
    },
    {
        id: 210,
        catId: 1,
        category: 'Women',
        company: 'Raymond',
        color: 'Orange',
        size: 'One Size',
        title: 'Black Single Breasted Super Slim Fit Blazer',
        price: 8000.00,
        description : 'Black solid single breasted blazer, has a notched lapel, long sleeves, three pockets, straight hem, attached satin lining. Set the trend with this blazer from Raymond. Team it up with trousers and a shirt to create a cool look.',
        subCat: 'Shirts',
        image: '../../assets/images/Products/Women/Western/Shirts/1.jpg',
        stock: 100
    },
    {
        id: 213,
        catId: 1,
        category: 'Women',
        company: 'Van Heusen',
        color: 'White',
        size: 'One Size',
        title: 'Blue Beat Relaxed Fit Low-Rise Light Fade Stretchable Jeans',
        price: 4499.00,
        description : 'Medium light fade blue jeans. For long-lasting comfort and style, opt for these Van Heusen skinny-fit jeans. They can be worn with canvas shoes and a stylish tee for a night out on the town with your friends.',
        subCat: 'Dresses',
        image: '../../assets/images/Products/Women/Western/Dresses/4.jpg',
        stock: 100
    },
    {
        id: 214,
        catId: 1,
        category: 'Women',
        company: 'Van Heusen',
        color: 'Black',
        size: 'One Size',
        title: 'Blue Beat Relaxed Fit Low-Rise Light Fade Stretchable Jeans',
        price: 3999.00,
        description : 'Medium light fade blue jeans. For long-lasting comfort and style, opt for these Van Heusen skinny-fit jeans. They can be worn with canvas shoes and a stylish tee for a night out on the town with your friends.',
        subCat: 'Dresses',
        image: '../../assets/images/Products/Women/Western/Dresses/2.jpg',
        stock: 100
    },
    {
        id: 215,
        catId: 1,
        category: 'Women',
        company: 'Van Heusen',
        color: 'White',
        size: 'One Size',
        title: 'Blue Beat Relaxed Fit Low-Rise Light Fade Stretchable Jeans',
        price: 2499.00,
        description : 'Medium light fade blue jeans. For long-lasting comfort and style, opt for these Van Heusen skinny-fit jeans. They can be worn with canvas shoes and a stylish tee for a night out on the town with your friends.',
        subCat: 'Dresses',
        image: '../../assets/images/Products/Women/Western/Dresses/3.jpg',
        stock: 100
    },
    {
        id: 216,
        catId: 1,
        category: 'Women',
        company: 'Van Heusen',
        color: 'White',
        size: 'One Size',
        title: 'Blue Beat Relaxed Fit Low-Rise Light Fade Stretchable Jeans',
        price: 499.00,
        description : 'Medium light fade blue jeans. For long-lasting comfort and style, opt for these Van Heusen skinny-fit jeans. They can be worn with canvas shoes and a stylish tee for a night out on the town with your friends.',
        subCat: 'Dresses',
        image: '../../assets/images/Products/Women/Western/Dresses/1.jpg',
        stock: 100
    },
    {
        id: 217,
        catId: 1,
        category: 'Women',
        company: 'Van Heusen',
        color: 'Red',
        size: 'One Size',
        title: 'Blue Beat Relaxed Fit Low-Rise Light Fade Stretchable Jeans',
        price: 1999.00,
        description : 'Medium light fade blue jeans. For long-lasting comfort and style, opt for these Van Heusen skinny-fit jeans. They can be worn with canvas shoes and a stylish tee for a night out on the town with your friends.',
        subCat: 'Dresses',
        image: '../../assets/images/Products/Women/Western/Dresses/5.jpg',
        stock: 100
    },
    {
        id: 218,
        catId: 1,
        category: 'Women',
        company: 'Van Heusen',
        color: 'Pink',
        size: 'One Size',
        title: 'Blue Beat Relaxed Fit Low-Rise Light Fade Stretchable Jeans',
        price: 499.00,
        description : 'Medium light fade blue jeans. For long-lasting comfort and style, opt for these Van Heusen skinny-fit jeans. They can be worn with canvas shoes and a stylish tee for a night out on the town with your friends.',
        subCat: 'Dresses',
        image: '../../assets/images/Products/Women/Western/Dresses/6.jpg',
        stock: 100
    },
    {
        id: 219,
        catId: 1,
        category: 'Women',
        company: 'Van Heusen',
        color: 'White',
        size: 'One Size',
        title: 'Blue Beat Relaxed Fit Low-Rise Light Fade Stretchable Jeans',
        price: 999.00,
        description : 'Medium light fade blue jeans. For long-lasting comfort and style, opt for these Van Heusen skinny-fit jeans. They can be worn with canvas shoes and a stylish tee for a night out on the town with your friends.',
        subCat: 'Dresses',
        image: '../../assets/images/Products/Women/Western/Dresses/7.jpg',
        stock: 100
    },
    {
        id: 231,
        catId: 0,
        category: 'Women',
        company: 'ONLY',
        color: 'Black',
        size: 'One Size',
        title: 'Black Single Breasted Super Slim Fit Blazer',
        price: 8000.00,
        description : 'Black solid single breasted blazer, has a notched lapel, long sleeves, three pockets, straight hem, attached satin lining. Set the trend with this blazer from Raymond. Team it up with trousers and a shirt to create a cool look.',
        subCat: 'Blazers',
        image: '../../assets/images/Products/Women/Western/Blazers/1.jpg',
        stock: 100
    },
    {
        id: 232,
        catId: 0,
        category: 'Women',
        company: 'Varanga',
        color: 'Pink',
        size: 'One Size',
        title: 'Black Single Breasted Super Slim Fit Blazer',
        price: 1999.00,
        description : 'Black solid single breasted blazer, has a notched lapel, long sleeves, three pockets, straight hem, attached satin lining. Set the trend with this blazer from Raymond. Team it up with trousers and a shirt to create a cool look.',
        subCat: 'Kurta Sets',
        image: '../../assets/images/Products/Women/Ethnic/Kurta Sets/1.jpg',
        stock: 100
    },
    {
        id: 241,
        catId: 0,
        category: 'Women',
        company: 'INDYA',
        color: 'Black',
        size: 'One Size',
        title: 'Black Single Breasted Super Slim Fit Blazer',
        price: 8000.00,
        description : 'Black solid single breasted blazer, has a notched lapel, long sleeves, three pockets, straight hem, attached satin lining. Set the trend with this blazer from Raymond. Team it up with trousers and a shirt to create a cool look.',
        subCat: 'Sarees',
        image: '../../assets/images/Products/Women/Ethnic/Sarees/1.jpg',
        stock: 100
    },
    {
        id: 242,
        catId: 0,
        category: 'Women',
        company: 'Anouk',
        color: 'Black',
        size: 'One Size',
        title: 'Black Single Breasted Super Slim Fit Blazer',
        price: 8000.00,
        description : 'Black solid single breasted blazer, has a notched lapel, long sleeves, three pockets, straight hem, attached satin lining. Set the trend with this blazer from Raymond. Team it up with trousers and a shirt to create a cool look.',
        subCat: 'Sarees',
        image: '../../assets/images/Products/Women/Ethnic/Sarees/2.jpg',
        stock: 100
    },
    {
        id: 244,
        catId: 0,
        category: 'Women',
        company: 'Libas',
        color: 'Black',
        size: 'One Size',
        title: 'Black Single Breasted Super Slim Fit Blazer',
        price: 8000.00,
        description : 'Black solid single breasted blazer, has a notched lapel, long sleeves, three pockets, straight hem, attached satin lining. Set the trend with this blazer from Raymond. Team it up with trousers and a shirt to create a cool look.',
        subCat: 'Lehenga Cholis',
        image: '../../assets/images/Products/Women/Ethnic/Lehenga/1.jpg',
        stock: 100
    },
    {
        id: 247,
        catId: 0,
        category: 'Women',
        company: 'Campus',
        color: 'Black',
        size: 'One Size',
        title: 'Black Single Breasted Super Slim Fit Blazer',
        price: 8000.00,
        description : 'Black solid single breasted blazer, has a notched lapel, long sleeves, three pockets, straight hem, attached satin lining. Set the trend with this blazer from Raymond. Team it up with trousers and a shirt to create a cool look.',
        subCat: 'Flip Flops',
        image: '../../assets/images/Products/Women/Footwear/Slippers/1.jpg',
        stock: 100
    },
    {
        id: 248,
        catId: 0,
        category: 'Women',
        company: 'Sparx',
        color: 'Black',
        size: 'One Size',
        title: 'Black Single Breasted Super Slim Fit Blazer',
        price: 8000.00,
        description : 'Black solid single breasted blazer, has a notched lapel, long sleeves, three pockets, straight hem, attached satin lining. Set the trend with this blazer from Raymond. Team it up with trousers and a shirt to create a cool look.',
        subCat: 'Flip Flops',
        image: '../../assets/images/Products/Women/Footwear/Slippers/2.jpg',
        stock: 100
    },
    {
        id: 249,
        catId: 0,
        category: 'Women',
        company: 'Bata',
        color: 'Black',
        size: 'One Size',
        title: 'Black Single Breasted Super Slim Fit Blazer',
        price: 8000.00,
        description : 'Black solid single breasted blazer, has a notched lapel, long sleeves, three pockets, straight hem, attached satin lining. Set the trend with this blazer from Raymond. Team it up with trousers and a shirt to create a cool look.',
        subCat: 'Flip Flops',
        image: '../../assets/images/Products/Women/Footwear/Slippers/3.jpg',
        stock: 100
    },
    {
        id: 261,
        catId: 0,
        category: 'Women',
        company: 'Roadster',
        color: 'Pink',
        size: 'One Size',
        title: 'Black Single Breasted Super Slim Fit Blazer',
        price: 8000.00,
        description : 'Black solid single breasted blazer, has a notched lapel, long sleeves, three pockets, straight hem, attached satin lining. Set the trend with this blazer from Raymond. Team it up with trousers and a shirt to create a cool look.',
        subCat: 'Shoes',
        image: '../../assets/images/Products/Women/Footwear/Shoes/1.jpg',
        stock: 100
    },
    {
        id: 261,
        catId: 0,
        category: 'Women',
        company: 'Roadster',
        color: 'Pink',
        size: 'One Size',
        title: 'Black Single Breasted Super Slim Fit Blazer',
        price: 8000.00,
        description : 'Black solid single breasted blazer, has a notched lapel, long sleeves, three pockets, straight hem, attached satin lining. Set the trend with this blazer from Raymond. Team it up with trousers and a shirt to create a cool look.',
        subCat: 'Heels',
        image: '../../assets/images/Products/Women/Footwear/Heels/1.jpg',
        stock: 100
    },
    {
        id: 261,
        catId: 0,
        category: 'Women',
        company: 'H&M',
        color: 'Pink',
        size: 'One Size',
        title: 'Black Single Breasted Super Slim Fit Blazer',
        price: 8000.00,
        description : 'Black solid single breasted blazer, has a notched lapel, long sleeves, three pockets, straight hem, attached satin lining. Set the trend with this blazer from Raymond. Team it up with trousers and a shirt to create a cool look.',
        subCat: 'Sandals',
        image: '../../assets/images/Products/Women/Footwear/Sandals/1.jpg',
        stock: 100
    },
    {
        id: 265,
        catId: 0,
        category: 'Women',
        company: 'Zaveri',
        color: 'Pink',
        size: 'One Size',
        title: 'Black Single Breasted Super Slim Fit Blazer',
        price: 8000.00,
        description : 'Black solid single breasted blazer, has a notched lapel, long sleeves, three pockets, straight hem, attached satin lining. Set the trend with this blazer from Raymond. Team it up with trousers and a shirt to create a cool look.',
        subCat: 'Jewellery',
        image: '../../assets/images/Products/Women/Accessories/Jewellery/1.jpg',
        stock: 100
    },
    {
        id: 270,
        catId: 0,
        category: 'Women',
        company: 'Roadster',
        color: 'Pink',
        size: 'One Size',
        title: 'Black Single Breasted Super Slim Fit Blazer',
        price: 8000.00,
        description : 'Black solid single breasted blazer, has a notched lapel, long sleeves, three pockets, straight hem, attached satin lining. Set the trend with this blazer from Raymond. Team it up with trousers and a shirt to create a cool look.',
        subCat: 'Scarves',
        image: '../../assets/images/Products/Women/Accessories/Scarves/1.jpg',
        stock: 100
    },
    {
        id: 275,
        catId: 0,
        category: 'Women',
        company: 'Allen Solly',
        color: 'Black',
        size: 'One Size',
        title: 'Black Single Breasted Super Slim Fit Blazer',
        price: 8000.00,
        description : 'Black solid single breasted blazer, has a notched lapel, long sleeves, three pockets, straight hem, attached satin lining. Set the trend with this blazer from Raymond. Team it up with trousers and a shirt to create a cool look.',
        subCat: 'Wallets & Handbags',
        image: '../../assets/images/Products/Women/Accessories/Wallets/1.jpg',
        stock: 100
    },
    {
        id: 301,
        catId: 0,
        category: 'Girls',
        company: 'Allen Solly',
        color: 'White',
        size: 'One Size',
        title: 'Black Single Breasted Super Slim Fit Blazer',
        price: 8000.00,
        description : 'Black solid single breasted blazer, has a notched lapel, long sleeves, three pockets, straight hem, attached satin lining. Set the trend with this blazer from Raymond. Team it up with trousers and a shirt to create a cool look.',
        subCat: 'Tshirts',
        image: '../../assets/images/Products/Kids/Girls/Tshirts/1.jpg',
        stock: 100
    },
    {
        id: 302,
        catId: 0,
        category: 'Girls',
        company: 'Kiddiess',
        color: 'White',
        size: 'One Size',
        title: 'Black Single Breasted Super Slim Fit Blazer',
        price: 8000.00,
        description : 'Black solid single breasted blazer, has a notched lapel, long sleeves, three pockets, straight hem, attached satin lining. Set the trend with this blazer from Raymond. Team it up with trousers and a shirt to create a cool look.',
        subCat: 'Tshirts',
        image: '../../assets/images/Products/Kids/Girls/Tshirts/3.jpg',
        stock: 100
    },
    {
        id: 306,
        catId: 0,
        category: 'Kids',
        company: 'Allen Solly',
        color: 'White',
        size: 'One Size',
        title: 'Black Single Breasted Super Slim Fit Blazer',
        price: 8000.00,
        description : 'Black solid single breasted blazer, has a notched lapel, long sleeves, three pockets, straight hem, attached satin lining. Set the trend with this blazer from Raymond. Team it up with trousers and a shirt to create a cool look.',
        subCat: 'Dresses',
        image: '../../assets/images/Products/Kids/Girls/Dresses/1.jpg',
        stock: 100
    },
    {
        id: 306,
        catId: 0,
        category: 'Kids',
        company: 'Allen Solly',
        color: 'White',
        size: 'One Size',
        title: 'Black Single Breasted Super Slim Fit Blazer',
        price: 8000.00,
        description : 'Black solid single breasted blazer, has a notched lapel, long sleeves, three pockets, straight hem, attached satin lining. Set the trend with this blazer from Raymond. Team it up with trousers and a shirt to create a cool look.',
        subCat: 'Dresses',
        image: '../../assets/images/Products/Kids/Girls/Dresses/2.jpg',
        stock: 100
    },
    {
        id: 306,
        catId: 0,
        category: 'Kids',
        company: 'Allen Solly',
        color: 'White',
        size: 'One Size',
        title: 'Black Single Breasted Super Slim Fit Blazer',
        price: 8000.00,
        description : 'Black solid single breasted blazer, has a notched lapel, long sleeves, three pockets, straight hem, attached satin lining. Set the trend with this blazer from Raymond. Team it up with trousers and a shirt to create a cool look.',
        subCat: 'Dresses',
        image: '../../assets/images/Products/Kids/Girls/Dresses/3.jpg',
        stock: 100
    },
    {
        id: 310,
        catId: 0,
        category: 'Kids',
        company: 'Allen Solly',
        color: 'White',
        size: 'One Size',
        title: 'Black Single Breasted Super Slim Fit Blazer',
        price: 8000.00,
        description : 'Black solid single breasted blazer, has a notched lapel, long sleeves, three pockets, straight hem, attached satin lining. Set the trend with this blazer from Raymond. Team it up with trousers and a shirt to create a cool look.',
        subCat: 'Trousers',
        image: '../../assets/images/Products/Kids/Girls/Trousers/1.jpg',
        stock: 100
    },
    {
        id: 310,
        catId: 0,
        category: 'Kids',
        company: 'Allen Solly',
        color: 'White',
        size: 'One Size',
        title: 'Black Single Breasted Super Slim Fit Blazer',
        price: 8000.00,
        description : 'Black solid single breasted blazer, has a notched lapel, long sleeves, three pockets, straight hem, attached satin lining. Set the trend with this blazer from Raymond. Team it up with trousers and a shirt to create a cool look.',
        subCat: 'Shoes',
        image: '../../assets/images/Products/Kids/Girls/Shoes/1.jpg',
        stock: 100
    },
    {
        id: 310,
        catId: 0,
        category: 'Kids',
        company: 'Allen Solly',
        color: 'Black',
        size: 'One Size',
        title: 'Black Single Breasted Super Slim Fit Blazer',
        price: 8000.00,
        description : 'Black solid single breasted blazer, has a notched lapel, long sleeves, three pockets, straight hem, attached satin lining. Set the trend with this blazer from Raymond. Team it up with trousers and a shirt to create a cool look.',
        subCat: 'Shoes',
        image: '../../assets/images/Products/Kids/Girls/Shoes/2.jpg',
        stock: 100
    },
    {
        id: 310,
        catId: 0,
        category: 'Boys',
        company: 'Allen Solly',
        color: 'Black',
        size: 'One Size',
        title: 'Black Single Breasted Super Slim Fit Blazer',
        price: 8000.00,
        description : 'Black solid single breasted blazer, has a notched lapel, long sleeves, three pockets, straight hem, attached satin lining. Set the trend with this blazer from Raymond. Team it up with trousers and a shirt to create a cool look.',
        subCat: 'Shoes',
        image: '../../assets/images/Products/Kids/Boys/Shoes/1.jpg',
        stock: 100
    },
    {
        id: 310,
        catId: 0,
        category: 'Kids',
        company: 'Allen Solly',
        color: 'Beige',
        size: 'One Size',
        title: 'Black Single Breasted Super Slim Fit Blazer',
        price: 8000.00,
        description : 'Black solid single breasted blazer, has a notched lapel, long sleeves, three pockets, straight hem, attached satin lining. Set the trend with this blazer from Raymond. Team it up with trousers and a shirt to create a cool look.',
        subCat: 'Sweatshirts',
        image: '../../assets/images/Products/Kids/Girls/Sweatshirts/1.jpg',
        stock: 100
    },
    {
        id: 310,
        catId: 0,
        category: 'Kids',
        company: 'Allen Solly',
        color: 'Pink',
        size: 'One Size',
        title: 'Black Single Breasted Super Slim Fit Blazer',
        price: 8000.00,
        description : 'Black solid single breasted blazer, has a notched lapel, long sleeves, three pockets, straight hem, attached satin lining. Set the trend with this blazer from Raymond. Team it up with trousers and a shirt to create a cool look.',
        subCat: 'Jackets',
        image: '../../assets/images/Products/Kids/Girls/Jackets/1.jpg',
        stock: 100
    },
    {
        id: 310,
        catId: 0,
        category: 'Kids',
        company: 'Peppermint',
        color: 'Blue',
        size: 'One Size',
        title: 'Black Single Breasted Super Slim Fit Blazer',
        price: 599.00,
        description : 'Black solid single breasted blazer, has a notched lapel, long sleeves, three pockets, straight hem, attached satin lining. Set the trend with this blazer from Raymond. Team it up with trousers and a shirt to create a cool look.',
        subCat: 'Skirts',
        image: '../../assets/images/Products/Kids/Girls/Skirts/1.jpg',
        stock: 100
    },
    {
        id: 315,
        catId: 0,
        category: 'Kids',
        company: 'Allen Solly',
        color: 'White',
        size: 'One Size',
        title: 'Black Single Breasted Super Slim Fit Blazer',
        price: 8000.00,
        description : 'Black solid single breasted blazer, has a notched lapel, long sleeves, three pockets, straight hem, attached satin lining. Set the trend with this blazer from Raymond. Team it up with trousers and a shirt to create a cool look.',
        subCat: 'Tshirts',
        image: '../../assets/images/Products/Kids/Boys/Tshirts/1.jpg',
        stock: 100
    },
    {
        id: 316,
        catId: 0,
        category: 'Kids',
        company: 'Allen Solly',
        color: 'White',
        size: 'One Size',
        title: 'Black Single Breasted Super Slim Fit Blazer',
        price: 8000.00,
        description : 'Black solid single breasted blazer, has a notched lapel, long sleeves, three pockets, straight hem, attached satin lining. Set the trend with this blazer from Raymond. Team it up with trousers and a shirt to create a cool look.',
        subCat: 'Tshirts',
        image: '../../assets/images/Products/Kids/Boys/Tshirts/2.jpg',
        stock: 100
    },
    {
        id: 316,
        catId: 0,
        category: 'Boys',
        company: 'Allen Solly',
        color: 'White',
        size: 'One Size',
        title: 'Black Single Breasted Super Slim Fit Blazer',
        price: 8000.00,
        description : 'Black solid single breasted blazer, has a notched lapel, long sleeves, three pockets, straight hem, attached satin lining. Set the trend with this blazer from Raymond. Team it up with trousers and a shirt to create a cool look.',
        subCat: 'Sweatshirts',
        image: '../../assets/images/Products/Kids/Boys/Sweatshirts/1.jpg',
        stock: 100
    },
    {
        id: 316,
        catId: 0,
        category: 'Kids',
        company: 'Allen Solly',
        color: 'White',
        size: 'One Size',
        title: 'Black Single Breasted Super Slim Fit Blazer',
        price: 8000.00,
        description : 'Black solid single breasted blazer, has a notched lapel, long sleeves, three pockets, straight hem, attached satin lining. Set the trend with this blazer from Raymond. Team it up with trousers and a shirt to create a cool look.',
        subCat: 'Sweaters',
        image: '../../assets/images/Products/Kids/Boys/Sweaters/1.jpg',
        stock: 100
    },
    {
        id: 316,
        catId: 0,
        category: 'Kids',
        company: 'Allen Solly',
        color: 'White',
        size: 'One Size',
        title: 'Black Single Breasted Super Slim Fit Blazer',
        price: 8000.00,
        description : 'Black solid single breasted blazer, has a notched lapel, long sleeves, three pockets, straight hem, attached satin lining. Set the trend with this blazer from Raymond. Team it up with trousers and a shirt to create a cool look.',
        subCat: 'Shirts',
        image: '../../assets/images/Products/Kids/Boys/Shirts/1.jpg',
        stock: 100
    },
    {
        id: 320,
        catId: 0,
        category: 'Kids',
        company: 'Allen Solly',
        color: 'White',
        size: 'One Size',
        title: 'Black Single Breasted Super Slim Fit Blazer',
        price: 8000.00,
        description : 'Black solid single breasted blazer, has a notched lapel, long sleeves, three pockets, straight hem, attached satin lining. Set the trend with this blazer from Raymond. Team it up with trousers and a shirt to create a cool look.',
        subCat: 'Toys',
        image: '../../assets/images/Products/Kids/Accessories/Toys/1.jpg',
        stock: 100
    },
    {
        id: 320,
        catId: 0,
        category: 'Kids',
        company: 'Allen Solly',
        color: 'White',
        size: 'One Size',
        title: 'Black Single Breasted Super Slim Fit Blazer',
        price: 8000.00,
        description : 'Black solid single breasted blazer, has a notched lapel, long sleeves, three pockets, straight hem, attached satin lining. Set the trend with this blazer from Raymond. Team it up with trousers and a shirt to create a cool look.',
        subCat: 'Toys',
        image: '../../assets/images/Products/Kids/Accessories/Toys/2.jpg',
        stock: 100
    },
    {
        id: 320,
        catId: 0,
        category: 'Kids',
        company: 'Allen Solly',
        color: 'White',
        size: 'One Size',
        title: 'Black Single Breasted Super Slim Fit Blazer',
        price: 8000.00,
        description : 'Black solid single breasted blazer, has a notched lapel, long sleeves, three pockets, straight hem, attached satin lining. Set the trend with this blazer from Raymond. Team it up with trousers and a shirt to create a cool look.',
        subCat: 'Toys',
        image: '../../assets/images/Products/Kids/Accessories/Toys/3.jpg',
        stock: 100
    },
    {
        id: 320,
        catId: 0,
        category: 'Kids',
        company: 'Allen Solly',
        color: 'White',
        size: 'One Size',
        title: 'Black Single Breasted Super Slim Fit Blazer',
        price: 8000.00,
        description : 'Black solid single breasted blazer, has a notched lapel, long sleeves, three pockets, straight hem, attached satin lining. Set the trend with this blazer from Raymond. Team it up with trousers and a shirt to create a cool look.',
        subCat: 'Toys',
        image: '../../assets/images/Products/Kids/Accessories/Toys/4.jpg',
        stock: 100
    },
    {
        id: 320,
        catId: 0,
        category: 'Kids',
        company: 'Allen Solly',
        color: 'White',
        size: 'One Size',
        title: 'Black Single Breasted Super Slim Fit Blazer',
        price: 8000.00,
        description : 'Black solid single breasted blazer, has a notched lapel, long sleeves, three pockets, straight hem, attached satin lining. Set the trend with this blazer from Raymond. Team it up with trousers and a shirt to create a cool look.',
        subCat: 'Caps',
        image: '../../assets/images/Products/Kids/Accessories/Caps/1.jpg',
        stock: 100
    },
    {
        id: 320,
        catId: 0,
        category: 'Kids',
        company: 'Allen Solly',
        color: 'Multicolor',
        size: 'One Size',
        title: 'Black Single Breasted Super Slim Fit Blazer',
        price: 8000.00,
        description : 'Black solid single breasted blazer, has a notched lapel, long sleeves, three pockets, straight hem, attached satin lining. Set the trend with this blazer from Raymond. Team it up with trousers and a shirt to create a cool look.',
        subCat: 'Crayons',
        image: '../../assets/images/Products/Kids/Accessories/Crayons/1.jpg',
        stock: 100
    },
    {
        id: 320,
        catId: 0,
        category: 'Kids',
        company: 'Allen Solly',
        color: 'White',
        size: 'One Size',
        title: 'Black Single Breasted Super Slim Fit Blazer',
        price: 8000.00,
        description : 'Black solid single breasted blazer, has a notched lapel, long sleeves, three pockets, straight hem, attached satin lining. Set the trend with this blazer from Raymond. Team it up with trousers and a shirt to create a cool look.',
        subCat: 'Backpacks',
        image: '../../assets/images/Products/Kids/Accessories/Backpacks/1.jpg',
        stock: 100
    },
    {
        id: 501,
        catId: 0,
        category: 'Electronics',
        company: 'Samsung',
        color: 'White',
        size: 'One Size',
        title: 'Black Single Breasted Super Slim Fit Blazer',
        price: 8000.00,
        description : 'Black solid single breasted blazer, has a notched lapel, long sleeves, three pockets, straight hem, attached satin lining. Set the trend with this blazer from Raymond. Team it up with trousers and a shirt to create a cool look.',
        subCat: 'Smart Phones',
        image: '../../assets/images/Products/Electronics/Mobiles/Smartphones/1.jpg',
        stock: 100
    },
    {
        id: 501,
        catId: 0,
        category: 'Electronics',
        company: 'Samsung',
        color: 'White',
        size: 'One Size',
        title: 'Black Single Breasted Super Slim Fit Blazer',
        price: 8000.00,
        description : 'Black solid single breasted blazer, has a notched lapel, long sleeves, three pockets, straight hem, attached satin lining. Set the trend with this blazer from Raymond. Team it up with trousers and a shirt to create a cool look.',
        subCat: 'DSLRs',
        image: '../../assets/images/Products/Electronics/1.jpg',
        stock: 100
    },
    {
        id: 501,
        catId: 0,
        category: 'Electronics',
        company: 'Samsung',
        color: 'White',
        size: 'One Size',
        title: 'Black Single Breasted Super Slim Fit Blazer',
        price: 8000.00,
        description : 'Black solid single breasted blazer, has a notched lapel, long sleeves, three pockets, straight hem, attached satin lining. Set the trend with this blazer from Raymond. Team it up with trousers and a shirt to create a cool look.',
        subCat: 'Gaming Laptops',
        image: '../../assets/images/Products/Electronics/2.jpg',
        stock: 100
    },
    {
        id: 501,
        catId: 0,
        category: 'Electronics',
        company: 'Samsung',
        color: 'White',
        size: 'One Size',
        title: 'Black Single Breasted Super Slim Fit Blazer',
        price: 8000.00,
        description : 'Black solid single breasted blazer, has a notched lapel, long sleeves, three pockets, straight hem, attached satin lining. Set the trend with this blazer from Raymond. Team it up with trousers and a shirt to create a cool look.',
        subCat: 'Camera Lenses',
        image: '../../assets/images/Products/Electronics/3.jpg',
        stock: 100
    },
    {
        id: 501,
        catId: 0,
        category: 'Electronics',
        company: 'Samsung',
        color: 'White',
        size: 'One Size',
        title: 'Black Single Breasted Super Slim Fit Blazer',
        price: 8000.00,
        description : 'Black solid single breasted blazer, has a notched lapel, long sleeves, three pockets, straight hem, attached satin lining. Set the trend with this blazer from Raymond. Team it up with trousers and a shirt to create a cool look.',
        subCat: 'Budget Laptops',
        image: '../../assets/images/Products/Electronics/4.jpg',
        stock: 100
    },
    {
        id: 501,
        catId: 0,
        category: 'Electronics',
        company: 'Samsung',
        color: 'White',
        size: 'One Size',
        title: 'Black Single Breasted Super Slim Fit Blazer',
        price: 8000.00,
        description : 'Black solid single breasted blazer, has a notched lapel, long sleeves, three pockets, straight hem, attached satin lining. Set the trend with this blazer from Raymond. Team it up with trousers and a shirt to create a cool look.',
        subCat: 'Tripods',
        image: '../../assets/images/Products/Electronics/5.jpg',
        stock: 100
    },
    {
        id: 501,
        catId: 0,
        category: 'Electronics',
        company: 'Samsung',
        color: 'White',
        size: 'One Size',
        title: 'Black Single Breasted Super Slim Fit Blazer',
        price: 8000.00,
        description : 'Black solid single breasted blazer, has a notched lapel, long sleeves, three pockets, straight hem, attached satin lining. Set the trend with this blazer from Raymond. Team it up with trousers and a shirt to create a cool look.',
        subCat: 'Speakers',
        image: '../../assets/images/Products/Electronics/6.jpg',
        stock: 100
    },
    {
        id: 501,
        catId: 0,
        category: 'Electronics',
        company: 'Samsung',
        color: 'White',
        size: 'One Size',
        title: 'Black Single Breasted Super Slim Fit Blazer',
        price: 8000.00,
        description : 'Black solid single breasted blazer, has a notched lapel, long sleeves, three pockets, straight hem, attached satin lining. Set the trend with this blazer from Raymond. Team it up with trousers and a shirt to create a cool look.',
        subCat: 'Headphones',
        image: '../../assets/images/Products/Electronics/7.jpg',
        stock: 100
    },
    {
        id: 501,
        catId: 0,
        category: 'Electronics',
        company: 'Samsung',
        color: 'White',
        size: 'One Size',
        title: 'Black Single Breasted Super Slim Fit Blazer',
        price: 8000.00,
        description : 'Black solid single breasted blazer, has a notched lapel, long sleeves, three pockets, straight hem, attached satin lining. Set the trend with this blazer from Raymond. Team it up with trousers and a shirt to create a cool look.',
        subCat: 'Keyboards',
        image: '../../assets/images/Products/Electronics/8.jpg',
        stock: 100
    },
    {
        id: 501,
        catId: 0,
        category: 'Electronics',
        company: 'Samsung',
        color: 'White',
        size: 'One Size',
        title: 'Black Single Breasted Super Slim Fit Blazer',
        price: 8000.00,
        description : 'Black solid single breasted blazer, has a notched lapel, long sleeves, three pockets, straight hem, attached satin lining. Set the trend with this blazer from Raymond. Team it up with trousers and a shirt to create a cool look.',
        subCat: 'CCTV Cameras',
        image: '../../assets/images/Products/Electronics/9.jpg',
        stock: 100
    },
    {
        id: 506,
        catId: 0,
        category: 'Electronics',
        company: 'Allen Solly',
        color: 'White',
        size: 'One Size',
        title: 'Black Single Breasted Super Slim Fit Blazer',
        price: 8000.00,
        description : 'Black solid single breasted blazer, has a notched lapel, long sleeves, three pockets, straight hem, attached satin lining. Set the trend with this blazer from Raymond. Team it up with trousers and a shirt to create a cool look.',
        subCat: 'Basic Phones',
        image: '../../assets/images/Products/Electronics/Mobiles/Basic/1.jpg',
        stock: 100
    },
    {
        id: 507,
        catId: 0,
        category: 'Electronics',
        company: 'Allen Solly',
        color: 'White',
        size: 'One Size',
        title: 'Black Single Breasted Super Slim Fit Blazer',
        price: 8000.00,
        description : 'Black solid single breasted blazer, has a notched lapel, long sleeves, three pockets, straight hem, attached satin lining. Set the trend with this blazer from Raymond. Team it up with trousers and a shirt to create a cool look.',
        subCat: 'Basic Phones',
        image: '../../assets/images/Products/Electronics/Mobiles/Basic/2.jpg',
        stock: 100
    },
    {
        id: 508,
        catId: 0,
        category: 'Electronics',
        company: 'Allen Solly',
        color: 'White',
        size: 'One Size',
        title: 'Black Single Breasted Super Slim Fit Blazer',
        price: 8000.00,
        description : 'Black solid single breasted blazer, has a notched lapel, long sleeves, three pockets, straight hem, attached satin lining. Set the trend with this blazer from Raymond. Team it up with trousers and a shirt to create a cool look.',
        subCat: 'Basic Phones',
        image: '../../assets/images/Products/Electronics/Mobiles/Basic/3.jpg',
        stock: 100
    },
    {
        id: 401,
        catId: 0,
        category: 'Home Decor',
        company: 'Allen Solly',
        color: 'White',
        size: 'One Size',
        title: 'Black Single Breasted Super Slim Fit Blazer',
        price: 8000.00,
        description : 'Black solid single breasted blazer, has a notched lapel, long sleeves, three pockets, straight hem, attached satin lining. Set the trend with this blazer from Raymond. Team it up with trousers and a shirt to create a cool look.',
        subCat: 'Curtains',
        image: '../../assets/images/Products/Decor/Furnishing/Curtains/1.jpg',
        stock: 100
    },
    {
        id: 402,
        catId: 0,
        category: 'Home Decor',
        company: 'Allen Solly',
        color: 'White',
        size: 'One Size',
        title: 'Black Single Breasted Super Slim Fit Blazer',
        price: 8000.00,
        description : 'Black solid single breasted blazer, has a notched lapel, long sleeves, three pockets, straight hem, attached satin lining. Set the trend with this blazer from Raymond. Team it up with trousers and a shirt to create a cool look.',
        subCat: 'Curtains',
        image: '../../assets/images/Products/Decor/Furnishing/Curtains/2.jpg',
        stock: 100
    },
    {
        id: 403,
        catId: 0,
        category: 'Home Decor',
        company: 'Allen Solly',
        color: 'White',
        size: 'One Size',
        title: 'Black Single Breasted Super Slim Fit Blazer',
        price: 8000.00,
        description : 'Black solid single breasted blazer, has a notched lapel, long sleeves, three pockets, straight hem, attached satin lining. Set the trend with this blazer from Raymond. Team it up with trousers and a shirt to create a cool look.',
        subCat: 'Clocks',
        image: '../../assets/images/Products/Decor/Decor/Clock/1.jpg',
        stock: 100
    },
    {
        id: 404,
        catId: 0,
        category: 'Home Decor',
        company: 'Allen Solly',
        color: 'White',
        size: 'One Size',
        title: 'Black Single Breasted Super Slim Fit Blazer',
        price: 8000.00,
        description : 'Black solid single breasted blazer, has a notched lapel, long sleeves, three pockets, straight hem, attached satin lining. Set the trend with this blazer from Raymond. Team it up with trousers and a shirt to create a cool look.',
        subCat: 'Mirrors',
        image: '../../assets/images/Products/Decor/Decor/Mirrors/1.jpg',
        stock: 100
    },
    {
        id: 405,
        catId: 0,
        category: 'Home Decor',
        company: 'Allen Solly',
        color: 'White',
        size: 'One Size',
        title: 'Black Single Breasted Super Slim Fit Blazer',
        price: 8000.00,
        description : 'Black solid single breasted blazer, has a notched lapel, long sleeves, three pockets, straight hem, attached satin lining. Set the trend with this blazer from Raymond. Team it up with trousers and a shirt to create a cool look.',
        subCat: 'Mirrors',
        image: '../../assets/images/Products/Decor/Decor/Mirrors/2.jpg',
        stock: 100
    },
    {
        id: 406,
        catId: 0,
        category: 'Home Decor',
        company: 'Allen Solly',
        color: 'White',
        size: 'One Size',
        title: 'Black Single Breasted Super Slim Fit Blazer',
        price: 8000.00,
        description : 'Black solid single breasted blazer, has a notched lapel, long sleeves, three pockets, straight hem, attached satin lining. Set the trend with this blazer from Raymond. Team it up with trousers and a shirt to create a cool look.',
        subCat: 'Mirrors',
        image: '../../assets/images/Products/Decor/Decor/Mirrors/3.png',
        stock: 100
    },
    {
        id: 407,
        catId: 0,
        category: 'Home Decor',
        company: 'Allen Solly',
        color: 'White',
        size: 'One Size',
        title: 'Black Single Breasted Super Slim Fit Blazer',
        price: 8000.00,
        description : 'Black solid single breasted blazer, has a notched lapel, long sleeves, three pockets, straight hem, attached satin lining. Set the trend with this blazer from Raymond. Team it up with trousers and a shirt to create a cool look.',
        subCat: 'Bottles & Boxes',
        image: '../../assets/images/Products/Decor/Kitchenware/Bottles/1.jpg',
        stock: 100
    },
    {
        id: 408,
        catId: 0,
        category: 'Home Decor',
        company: 'Allen Solly',
        color: 'White',
        size: 'One Size',
        title: 'Black Single Breasted Super Slim Fit Blazer',
        price: 8000.00,
        description : 'Black solid single breasted blazer, has a notched lapel, long sleeves, three pockets, straight hem, attached satin lining. Set the trend with this blazer from Raymond. Team it up with trousers and a shirt to create a cool look.',
        subCat: 'Chopping Boards',
        image: '../../assets/images/Products/Decor/Kitchenware/Boards/1.png',
        stock: 100
    },
    {
        id: 409,
        catId: 0,
        category: 'Home Decor',
        company: 'Allen Solly',
        color: 'White',
        size: 'One Size',
        title: 'Black Single Breasted Super Slim Fit Blazer',
        price: 8000.00,
        description : 'Black solid single breasted blazer, has a notched lapel, long sleeves, three pockets, straight hem, attached satin lining. Set the trend with this blazer from Raymond. Team it up with trousers and a shirt to create a cool look.',
        subCat: 'Bedsheets',
        image: '../../assets/images/Products/Decor/Furnishing/Bedsheets/1.jpg',
        stock: 100
    },
    {
        id: 410,
        catId: 0,
        category: 'Home Decor',
        company: 'NIVAS',
        color: 'Black',
        size: 'One Size',
        title: 'Black Single Breasted Super Slim Fit Blazer',
        price: 8000.00,
        description : 'Black solid single breasted blazer, has a notched lapel, long sleeves, three pockets, straight hem, attached satin lining. Set the trend with this blazer from Raymond. Team it up with trousers and a shirt to create a cool look.',
        subCat: 'Blankets',
        image: '../../assets/images/Products/Decor/Furnishing/Blankets/1.jpg',
        stock: 100
    },
    {
        id: 411,
        catId: 0,
        category: 'Home Decor',
        company: 'Status',
        color: 'Red',
        size: 'One Size',
        title: 'Black Single Breasted Super Slim Fit Blazer',
        price: 8000.00,
        description : 'Black solid single breasted blazer, has a notched lapel, long sleeves, three pockets, straight hem, attached satin lining. Set the trend with this blazer from Raymond. Team it up with trousers and a shirt to create a cool look.',
        subCat: 'Carpets',
        image: '../../assets/images/Products/Decor/Furnishing/Carpets/1.jpg',
        stock: 100
    },
    {
        id: 412,
        catId: 0,
        category: 'Home Decor',
        company: 'Status',
        color: 'Red',
        size: 'One Size',
        title: 'Black Single Breasted Super Slim Fit Blazer',
        price: 8000.00,
        description : 'Black solid single breasted blazer, has a notched lapel, long sleeves, three pockets, straight hem, attached satin lining. Set the trend with this blazer from Raymond. Team it up with trousers and a shirt to create a cool look.',
        subCat: 'Photo Frames',
        image: '../../assets/images/Products/Decor/Decor/Frames/1.jpg',
        stock: 100
    },
    {
        id: 413,
        catId: 0,
        category: 'Home Decor',
        company: 'Status',
        color: 'Red',
        size: 'One Size',
        title: 'Black Single Breasted Super Slim Fit Blazer',
        price: 8000.00,
        description : 'Black solid single breasted blazer, has a notched lapel, long sleeves, three pockets, straight hem, attached satin lining. Set the trend with this blazer from Raymond. Team it up with trousers and a shirt to create a cool look.',
        subCat: 'Paintings',
        image: '../../assets/images/Products/Decor/Decor/Paintings/1.jpg',
        stock: 100
    },
    {
        id: 490,
        catId: 0,
        category: 'Home Decor',
        company: 'Status',
        color: 'White',
        size: 'One Size',
        title: 'Black Single Breasted Super Slim Fit Blazer',
        price: 8000.00,
        description : 'Black solid single breasted blazer, has a notched lapel, long sleeves, three pockets, straight hem, attached satin lining. Set the trend with this blazer from Raymond. Team it up with trousers and a shirt to create a cool look.',
        subCat: 'Dinner Sets',
        image: '../../assets/images/Products/Decor/Kitchenware/Dinner Sets/1.jpg',
        stock: 100
    },
    {
        id: 414,
        catId: 0,
        category: 'Home Decor',
        company: 'Status',
        color: 'Red',
        size: 'One Size',
        title: 'Black Single Breasted Super Slim Fit Blazer',
        price: 8000.00,
        description : 'Black solid single breasted blazer, has a notched lapel, long sleeves, three pockets, straight hem, attached satin lining. Set the trend with this blazer from Raymond. Team it up with trousers and a shirt to create a cool look.',
        subCat: 'Containers',
        image: '../../assets/images/Products/Decor/Kitchenware/Containers/1.jpg',
        stock: 100
    },
    {
        id: 415,
        catId: 0,
        category: 'Home Decor',
        company: 'Status',
        color: 'Red',
        size: 'One Size',
        title: 'Black Single Breasted Super Slim Fit Blazer',
        price: 8000.00,
        description : 'Black solid single breasted blazer, has a notched lapel, long sleeves, three pockets, straight hem, attached satin lining. Set the trend with this blazer from Raymond. Team it up with trousers and a shirt to create a cool look.',
        subCat: 'Laundry Bags',
        image: '../../assets/images/Products/Decor/Bath/Laundrybags/1.jpg',
        stock: 100
    },
    {
        id: 416,
        catId: 0,
        category: 'Home Decor',
        company: 'Status',
        color: 'Red',
        size: 'One Size',
        title: 'Black Single Breasted Super Slim Fit Blazer',
        price: 8000.00,
        description : 'Black solid single breasted blazer, has a notched lapel, long sleeves, three pockets, straight hem, attached satin lining. Set the trend with this blazer from Raymond. Team it up with trousers and a shirt to create a cool look.',
        subCat: 'Laundry Bags',
        image: '../../assets/images/Products/Decor/Bath/Laundrybags/2.jpg',
        stock: 100
    },
    {
        id: 417,
        catId: 0,
        category: 'Home Decor',
        company: 'Status',
        color: 'Red',
        size: 'One Size',
        title: 'Black Single Breasted Super Slim Fit Blazer',
        price: 8000.00,
        description : 'Black solid single breasted blazer, has a notched lapel, long sleeves, three pockets, straight hem, attached satin lining. Set the trend with this blazer from Raymond. Team it up with trousers and a shirt to create a cool look.',
        subCat: 'Soap Dispensers',
        image: '../../assets/images/Products/Decor/Bath/Dispenser/1.jpg',
        stock: 100
    },
    {
        id: 418,
        catId: 0,
        category: 'Home Decor',
        company: 'Status',
        color: 'Red',
        size: 'One Size',
        title: 'Black Single Breasted Super Slim Fit Blazer',
        price: 8000.00,
        description : 'Black solid single breasted blazer, has a notched lapel, long sleeves, three pockets, straight hem, attached satin lining. Set the trend with this blazer from Raymond. Team it up with trousers and a shirt to create a cool look.',
        subCat: 'Toothbrush Holders',
        image: '../../assets/images/Products/Decor/Bath/Holders/1.jpg',
        stock: 100
    },
    {
        id: 419,
        catId: 0,
        category: 'Home Decor',
        company: 'Status',
        color: 'Red',
        size: 'One Size',
        title: 'Black Single Breasted Super Slim Fit Blazer',
        price: 8000.00,
        description : 'Black solid single breasted blazer, has a notched lapel, long sleeves, three pockets, straight hem, attached satin lining. Set the trend with this blazer from Raymond. Team it up with trousers and a shirt to create a cool look.',
        subCat: 'Bathroom Trays',
        image: '../../assets/images/Products/Decor/Bath/Trays/1.jpg',
        stock: 100
    },
    {
        id: 420,
        catId: 0,
        category: 'Home Decor',
        company: 'Status',
        color: 'Red',
        size: 'One Size',
        title: 'Black Single Breasted Super Slim Fit Blazer',
        price: 8000.00,
        description : 'Black solid single breasted blazer, has a notched lapel, long sleeves, three pockets, straight hem, attached satin lining. Set the trend with this blazer from Raymond. Team it up with trousers and a shirt to create a cool look.',
        subCat: 'Bathroom Trays',
        image: '../../assets/images/Products/Decor/Bath/Trays/2.jpg',
        stock: 100
    },
    {
        id: 420,
        catId: 6,
        category: 'Gifts',
        company: 'Grafity',
        color: 'Red',
        size: 'One Size',
        title: 'Black Single Breasted Super Slim Fit Blazer',
        price: 2999.00,
        description : 'Black solid single breasted blazer, has a notched lapel, long sleeves, three pockets, straight hem, attached satin lining. Set the trend with this blazer from Raymond. Team it up with trousers and a shirt to create a cool look.',
        subCat: 'Artificial Flowers',
        image: '../../assets/images/Products/Gifts/1.jpg',
        stock: 100
    },
    {
        id: 420,
        catId: 6,
        category: 'Gifts',
        company: 'Grafity',
        color: 'Red',
        size: 'One Size',
        title: 'Black Single Breasted Super Slim Fit Blazer',
        price: 2999.00,
        description : 'Black solid single breasted blazer, has a notched lapel, long sleeves, three pockets, straight hem, attached satin lining. Set the trend with this blazer from Raymond. Team it up with trousers and a shirt to create a cool look.',
        subCat: 'Candles',
        image: '../../assets/images/Products/Gifts/2.jpg',
        stock: 100
    },
    {
        id: 420,
        catId: 6,
        category: 'Gifts',
        company: 'Grafity',
        color: 'Red',
        size: 'One Size',
        title: 'Black Single Breasted Super Slim Fit Blazer',
        price: 2999.00,
        description : 'Black solid single breasted blazer, has a notched lapel, long sleeves, three pockets, straight hem, attached satin lining. Set the trend with this blazer from Raymond. Team it up with trousers and a shirt to create a cool look.',
        subCat: 'Jewellery Set',
        image: '../../assets/images/Products/Gifts/3.jpg',
        stock: 100
    },
    {
        id: 420,
        catId: 6,
        category: 'Gifts',
        company: 'Grafity',
        color: 'Red',
        size: 'One Size',
        title: 'Black Single Breasted Super Slim Fit Blazer',
        price: 2999.00,
        description : 'Black solid single breasted blazer, has a notched lapel, long sleeves, three pockets, straight hem, attached satin lining. Set the trend with this blazer from Raymond. Team it up with trousers and a shirt to create a cool look.',
        subCat: 'Soft Toys',
        image: '../../assets/images/Products/Gifts/4.jpg',
        stock: 100
    },
    {
        id: 420,
        catId: 6,
        category: 'Gifts',
        company: 'Grafity',
        color: 'Red',
        size: 'One Size',
        title: 'Black Single Breasted Super Slim Fit Blazer',
        price: 2999.00,
        description : 'Black solid single breasted blazer, has a notched lapel, long sleeves, three pockets, straight hem, attached satin lining. Set the trend with this blazer from Raymond. Team it up with trousers and a shirt to create a cool look.',
        subCat: 'Diary',
        image: '../../assets/images/Products/Gifts/5.jpg',
        stock: 100
    },
    {
        id: 420,
        catId: 6,
        category: 'Gifts',
        company: 'Grafity',
        color: 'Red',
        size: 'One Size',
        title: 'Black Single Breasted Super Slim Fit Blazer',
        price: 2999.00,
        description : 'Black solid single breasted blazer, has a notched lapel, long sleeves, three pockets, straight hem, attached satin lining. Set the trend with this blazer from Raymond. Team it up with trousers and a shirt to create a cool look.',
        subCat: 'Watches',
        image: '../../assets/images/Products/Gifts/6.jpg',
        stock: 100
    },
    {
        id: 420,
        catId: 6,
        category: 'Gifts',
        company: 'Grafity',
        color: 'Red',
        size: 'One Size',
        title: 'Black Single Breasted Super Slim Fit Blazer',
        price: 2999.00,
        description : 'Black solid single breasted blazer, has a notched lapel, long sleeves, three pockets, straight hem, attached satin lining. Set the trend with this blazer from Raymond. Team it up with trousers and a shirt to create a cool look.',
        subCat: 'Flower Vase',
        image: '../../assets/images/Products/Gifts/7.jpg',
        stock: 100
    },
    {
        id: 420,
        catId: 6,
        category: 'Gifts',
        company: 'Grafity',
        color: 'Red',
        size: 'One Size',
        title: 'Black Single Breasted Super Slim Fit Blazer',
        price: 2999.00,
        description : 'Black solid single breasted blazer, has a notched lapel, long sleeves, three pockets, straight hem, attached satin lining. Set the trend with this blazer from Raymond. Team it up with trousers and a shirt to create a cool look.',
        subCat: 'Cards',
        image: '../../assets/images/Products/Gifts/8.jpg',
        stock: 100
    },
    {
        id: 420,
        catId: 6,
        category: 'Gifts',
        company: 'Grafity',
        color: 'Red',
        size: 'One Size',
        title: 'Black Single Breasted Super Slim Fit Blazer',
        price: 2999.00,
        description : 'Black solid single breasted blazer, has a notched lapel, long sleeves, three pockets, straight hem, attached satin lining. Set the trend with this blazer from Raymond. Team it up with trousers and a shirt to create a cool look.',
        subCat: 'Pens',
        image: '../../assets/images/Products/Gifts/9.jpg',
        stock: 100
    },
    {
        id: 420,
        catId: 6,
        category: 'Gifts',
        company: 'Grafity',
        color: 'Red',
        size: 'One Size',
        title: 'Black Single Breasted Super Slim Fit Blazer',
        price: 2999.00,
        description : 'Black solid single breasted blazer, has a notched lapel, long sleeves, three pockets, straight hem, attached satin lining. Set the trend with this blazer from Raymond. Team it up with trousers and a shirt to create a cool look.',
        subCat: 'Dream Catchers',
        image: '../../assets/images/Products/Gifts/10.jpg',
        stock: 100
    },
    {
        id: 420,
        catId: 6,
        category: 'Gifts',
        company: 'Grafity',
        color: 'Red',
        size: 'One Size',
        title: 'Black Single Breasted Super Slim Fit Blazer',
        price: 2999.00,
        description : 'Black solid single breasted blazer, has a notched lapel, long sleeves, three pockets, straight hem, attached satin lining. Set the trend with this blazer from Raymond. Team it up with trousers and a shirt to create a cool look.',
        subCat: 'Showpieces',
        image: '../../assets/images/Products/Gifts/11.jpg',
        stock: 100
    },
    {
        id: 420,
        catId: 6,
        category: 'Gifts',
        company: 'Grafity',
        color: 'Red',
        size: 'One Size',
        title: 'Black Single Breasted Super Slim Fit Blazer',
        price: 2999.00,
        description : 'Black solid single breasted blazer, has a notched lapel, long sleeves, three pockets, straight hem, attached satin lining. Set the trend with this blazer from Raymond. Team it up with trousers and a shirt to create a cool look.',
        subCat: 'Pen Stand',
        image: '../../assets/images/Products/Gifts/12.jpg',
        stock: 100
    },
    {
        id: 420,
        catId: 6,
        category: 'Gifts',
        company: 'Grafity',
        color: 'Red',
        size: 'One Size',
        title: 'Black Single Breasted Super Slim Fit Blazer',
        price: 2999.00,
        description : 'Black solid single breasted blazer, has a notched lapel, long sleeves, three pockets, straight hem, attached satin lining. Set the trend with this blazer from Raymond. Team it up with trousers and a shirt to create a cool look.',
        subCat: 'Candies',
        image: '../../assets/images/Products/Gifts/13.jpg',
        stock: 100
    },
    {
        id: 420,
        catId: 6,
        category: 'Gifts',
        company: 'Grafity',
        color: 'Red',
        size: 'One Size',
        title: 'Black Single Breasted Super Slim Fit Blazer',
        price: 2999.00,
        description : 'Black solid single breasted blazer, has a notched lapel, long sleeves, three pockets, straight hem, attached satin lining. Set the trend with this blazer from Raymond. Team it up with trousers and a shirt to create a cool look.',
        subCat: 'Mugs',
        image: '../../assets/images/Products/Gifts/14.jpg',
        stock: 100
    },



    {
        id: 420,
        catId: 5,
        category: 'Personal Care',
        company: 'Grafity',
        color: 'Red',
        size: 'One Size',
        title: 'Black Single Breasted Super Slim Fit Blazer',
        price: 2999.00,
        description : 'Black solid single breasted blazer, has a notched lapel, long sleeves, three pockets, straight hem, attached satin lining. Set the trend with this blazer from Raymond. Team it up with trousers and a shirt to create a cool look.',
        subCat: 'Moisturizers',
            image: '../../assets/images/Products/Care/1.jpg',
            stock: 100
    },
    {
        id: 420,
        catId: 5,
        category: 'Personal Care',
        company: 'Grafity',
        color: 'Red',
        size: 'One Size',
        title: 'Black Single Breasted Super Slim Fit Blazer',
        price: 2999.00,
        description : 'Black solid single breasted blazer, has a notched lapel, long sleeves, three pockets, straight hem, attached satin lining. Set the trend with this blazer from Raymond. Team it up with trousers and a shirt to create a cool look.',
        subCat: 'Nail Polish',
            image: '../../assets/images/Products/Care/2.jpg',
            stock: 100
    },
    {
        id: 420,
        catId: 5,
        category: 'Personal Care',
        company: 'Grafity',
        color: 'Red',
        size: 'One Size',
        title: 'Black Single Breasted Super Slim Fit Blazer',
        price: 2999.00,
        description : 'Black solid single breasted blazer, has a notched lapel, long sleeves, three pockets, straight hem, attached satin lining. Set the trend with this blazer from Raymond. Team it up with trousers and a shirt to create a cool look.',
        subCat: 'Perfumes',
            image: '../../assets/images/Products/Care/3.jpg',
            stock: 100
    },
    {
        id: 420,
        catId: 5,
        category: 'Personal Care',
        company: 'Grafity',
        color: 'Red',
        size: 'One Size',
        title: 'Black Single Breasted Super Slim Fit Blazer',
        price: 2999.00,
        description : 'Black solid single breasted blazer, has a notched lapel, long sleeves, three pockets, straight hem, attached satin lining. Set the trend with this blazer from Raymond. Team it up with trousers and a shirt to create a cool look.',
        subCat: 'Body Oil',
            image: '../../assets/images/Products/Care/4.jpg',
            stock: 100
    },
    {
        id: 420,
        catId: 5,
        category: 'Personal Care',
        company: 'Grafity',
        color: 'Red',
        size: 'One Size',
        title: 'Black Single Breasted Super Slim Fit Blazer',
        price: 2999.00,
        description : 'Black solid single breasted blazer, has a notched lapel, long sleeves, three pockets, straight hem, attached satin lining. Set the trend with this blazer from Raymond. Team it up with trousers and a shirt to create a cool look.',
        subCat: 'Body Scrub',
            image: '../../assets/images/Products/Care/5.jpg',
            stock: 100
    },
    {
        id: 420,
        catId: 5,
        category: 'Personal Care',
        company: 'Grafity',
        color: 'Red',
        size: 'One Size',
        title: 'Black Single Breasted Super Slim Fit Blazer',
        price: 2999.00,
        description : 'Black solid single breasted blazer, has a notched lapel, long sleeves, three pockets, straight hem, attached satin lining. Set the trend with this blazer from Raymond. Team it up with trousers and a shirt to create a cool look.',
        subCat: 'Sanitizers',
            image: '../../assets/images/Products/Care/6.jpg',
            stock: 100
    },
    {
        id: 420,
        catId: 5,
        category: 'Personal Care',
        company: 'Grafity',
        color: 'Red',
        size: 'One Size',
        title: 'Black Single Breasted Super Slim Fit Blazer',
        price: 2999.00,
        description : 'Black solid single breasted blazer, has a notched lapel, long sleeves, three pockets, straight hem, attached satin lining. Set the trend with this blazer from Raymond. Team it up with trousers and a shirt to create a cool look.',
        subCat: 'Shaving Cream',
            image: '../../assets/images/Products/Care/7.jpg',
            stock: 100
    },
    {
        id: 420,
        catId: 5,
        category: 'Personal Care',
        company: 'Grafity',
        color: 'Red',
        size: 'One Size',
        title: 'Black Single Breasted Super Slim Fit Blazer',
        price: 2999.00,
        description : 'Black solid single breasted blazer, has a notched lapel, long sleeves, three pockets, straight hem, attached satin lining. Set the trend with this blazer from Raymond. Team it up with trousers and a shirt to create a cool look.',
        subCat: 'Deodorants',
            image: '../../assets/images/Products/Care/8.jpg',
            stock: 100
    },
    {
        id: 420,
        catId: 5,
        category: 'Personal Care',
        company: 'Grafity',
        color: 'Red',
        size: 'One Size',
        title: 'Black Single Breasted Super Slim Fit Blazer',
        price: 2999.00,
        description : 'Black solid single breasted blazer, has a notched lapel, long sleeves, three pockets, straight hem, attached satin lining. Set the trend with this blazer from Raymond. Team it up with trousers and a shirt to create a cool look.',
        subCat: 'Hair Dryer',
            image: '../../assets/images/Products/Care/9.jpg',
            stock: 100
    },
    {
        id: 420,
        catId: 5,
        category: 'Personal Care',
        company: 'Grafity',
        color: 'Red',
        size: 'One Size',
        title: 'Black Single Breasted Super Slim Fit Blazer',
        price: 2999.00,
        description : 'Black solid single breasted blazer, has a notched lapel, long sleeves, three pockets, straight hem, attached satin lining. Set the trend with this blazer from Raymond. Team it up with trousers and a shirt to create a cool look.',
        subCat: 'Trimmers',
            image: '../../assets/images/Products/Care/10.jpg',
            stock: 100
    },
    {
        id: 420,
        catId: 5,
        category: 'Personal Care',
        company: 'Grafity',
        color: 'Red',
        size: 'One Size',
        title: 'Black Single Breasted Super Slim Fit Blazer',
        price: 2999.00,
        description : 'Black solid single breasted blazer, has a notched lapel, long sleeves, three pockets, straight hem, attached satin lining. Set the trend with this blazer from Raymond. Team it up with trousers and a shirt to create a cool look.',
        subCat: 'Shampoo',
            image: '../../assets/images/Products/Care/11.jpg',
            stock: 100
    },
    {
        id: 420,
        catId: 5,
        category: 'Personal Care',
        company: 'Grafity',
        color: 'Red',
        size: 'One Size',
        title: 'Black Single Breasted Super Slim Fit Blazer',
        price: 2999.00,
        description : 'Black solid single breasted blazer, has a notched lapel, long sleeves, three pockets, straight hem, attached satin lining. Set the trend with this blazer from Raymond. Team it up with trousers and a shirt to create a cool look.',
        subCat: 'Conditioner',
            image: '../../assets/images/Products/Care/12.jpg',
            stock: 100
    },
];
